In [37]:
import numpy as np
import math

sentence_tokens = ["the", "earth", "is", "round"]
word_to_index = {word: i for i, word in enumerate(sentence_tokens)}
#np.eye creates a diagnol matrix
one_hot_encoding = np.eye(len(word_to_index))

In [38]:
word_to_index

{'the': 0, 'earth': 1, 'is': 2, 'round': 3}

In [39]:
one_hot_encoding

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
W_Q = np.array([
     [0.1, 0.2, 0.3],
     [0.4, 0.5, 0.6],
     [0.7, 0.8, 0.9],
     [1.0, 1.1, 1.2],
],dtype=float)

Q = one_hot_encoding @ W_Q
print(Q)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [1.  1.1 1.2]]


In [41]:
W_K = np.array([
    [0.4, 0.5, 0.6],
    [0.1, 0.2, 0.3],
    [1.0, 1.1, 1.2],
    [0.7, 0.8, 0.9],
],dtype=float)

K = one_hot_encoding @ W_K
print(K)

[[0.4 0.5 0.6]
 [0.1 0.2 0.3]
 [1.  1.1 1.2]
 [0.7 0.8 0.9]]


In [42]:
W_V = np.array([
    [0.1, 0.2, 0.3],
    [1.0, 1.1, 1.2],
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
],dtype=float)

V = one_hot_encoding @ W_V
print(V)

[[0.1 0.2 0.3]
 [1.  1.1 1.2]
 [0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [43]:
QKt = Q @ K.T
d_k = K.shape[1]
scaled_scores = QKt / np.sqrt(d_k)

In [44]:
def softmax_score(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)

In [45]:
attn = softmax_score(scaled_scores)

In [46]:
out = attn @ V

In [47]:

print("Final attention outputs (attn @ V):\n", out, "\n")


Final attention outputs (attn @ V):
 [[0.36969935 0.46969935 0.56969935]
 [0.32805318 0.42805318 0.52805318]
 [0.2916227  0.3916227  0.4916227 ]
 [0.26060479 0.36060479 0.46060479]] 

